config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :projects do
    resources :tasks
  end

  authenticated :user do
    root 'projects#index', as: 'authenticated_root'
  end

  root 'homes#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @user = current_user
    @projects = Project.where(user: @user)
  end

  def new
    @project = Project.new
  end

  def create
    @user = current_user
    @project = Project.new(project_params)
    @project.user = @user

    if @project.save
      flash[:notice] = 'Sucessfully Added'
      redirect_to projects_path
    else
      flash[:notice] = @project.errors.full_messages.join('. ')
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      flash[:notice] = 'Successfully Updated'
      redirect_to projects_path
    else
      flash[:notice] = @project.errors.full_messages.join('. ')
      render :edit
    end
  end

  def show
    @project = Project.find(params[:id])
    @task = Task.new
    @tasks = @project.tasks.order(number: :asc)
  end

  def destroy
    Project.find(params[:id]).destroy
    flash[:notice] = 'Successfully Deleted'
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :duration, :start, :finish)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @project = Project.find_by(id: params[:project_id])
    @task.project = @project

    if @task.save
      flash[:notice] = 'Sucessfully Added'
      redirect_to project_path(@project)
    else
      flash[:notice] = @task.errors.full_messages.join('. ')
      render project_path(@project)
    end
  end

  def edit
    @task = Task.find(params[:id])
    @project = Project.find_by(id: params[:project_id])
  end

  def update
    @task = Task.find(params[:id])
    @project = Project.find_by(id: params[:project_id])
    if @task.update_attributes(task_params)
      flash[:notice] = 'Successfully Updated'
      redirect_to project_path(@project)
    else
      flash[:notice] = @task.errors.full_messages.join('. ')
      render :edit
    end
  end

  def destroy
    @project = Project.find_by(id: params[:project_id])
    Task.find(params[:id]).destroy
    flash[:notice] = 'Successfully Deleted'
    redirect_to project_path(@project)
  end

  private

  def task_params
    params.require(:task).permit(:number, :name, :duration, :start, :finish, :predecessors, :resources)
  end

end

app/views/homes/index.html.erb
<p>
  Welcome to Timeline.

  <% if !current_user.nil? %>
    <p><%= link_to 'See projects', projects_path %></p>
  <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timeline</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Timeline</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to current_user.email, root_path %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/projects/edit.html.erb
<h2>this is the edit page for projects</h2>

<p><%= link_to 'Back to projects', projects_path %></p>

<table>
  <tr>
    <th>Name</th>
    <th>Duration</th>
    <th>Start</th>
    <th>Finish</th>
  </tr>
  <%= form_for @project do |f| %>
    <tr>
      <td><%= f.text_field :name %></td>
      <td><%= f.text_field :duration %></td>
      <td><%= f.text_field :start %></td>
      <td><%= f.text_field :finish %></td>
      <td><%= f.submit 'Submit', class: "button round" %></td>
    </tr>
  <%- end -%>
</table>

app/views/projects/index.html.erb
<h2>This is the projects index page</h2>

<p><%= link_to 'Add a new project', new_project_path %></p>

<% if !@projects.empty? %>
  <table>
    <tr>
      <th>Name</th>
      <th>Duration</th>
      <th>Start</th>
      <th>Finish</th>
    </tr>

    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to "#{project.name}", project_path(project) %></td>
        <td><%= project.duration %></td>
        <td><%= project.start %></td>
        <td><%= project.finish %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Delete', project_path(project), method: :delete %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/projects/new.html.erb
<h2>this is the new page for projects</h2>

<p><%= link_to 'Back to projects', projects_path %></p>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <%= form_for @project do |f| %>
    <tr>
      <td><%= f.text_field :name %></td>
      <td><%= f.submit 'Submit', class: "button round" %></td>
    </tr>
  <%- end -%>
</table>

app/views/projects/show.html.erb
<h2>Project Name:  <%= @project.name %></h2>

<p><%= link_to 'Back to projects', projects_path %></p>

<% if !@tasks.empty? %>
  <table>
    <tr>
      <th>No.</th>
      <th>Name</th>
      <th>Duration</th>
      <th>Start</th>
      <th>Finish</th>
      <th>Predecessors</th>
      <th>Resources</th>
    </tr>

    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.number %></td>
        <td><%= task.name %></td>
        <td><%= task.duration %></td>
        <td><%= task.start %></td>
        <td><%= task.finish %></td>
        <td><%= task.predecessors %></td>
        <td><%= task.resources %></td>
        <td><%= link_to 'Edit', edit_project_task_path(@project, task) %></td>
        <td><%= link_to 'Delete', project_task_path(@project, task), method: :delete %></td>
      </tr>
    <% end %>
  </table>
<% end %>

<%= render 'tasks/new' %>

app/views/tasks/_new.html.erb
<table>
  <tr>
    <th>No.</th>
    <th>Name</th>
    <th>Duration</th>
    <th>Start</th>
    <th>Finish</th>
    <th>Predecessors</th>
    <th>Resources</th>
  </tr>
  <%= form_for [@project, @task] do |f| %>
    <tr>
      <td><%= f.text_field :number %></td>
      <td><%= f.text_field :name %></td>
      <td><%= f.text_field :duration %></td>
      <td><%= f.text_field :start %></td>
      <td><%= f.text_field :finish %></td>
      <td><%= f.text_field :predecessors %></td>
      <td><%= f.text_field :resources %></td>
      <td><%= f.submit 'Submit', class: "button round" %></td>
    </tr>
  <%- end -%>
</table>

app/views/tasks/edit.html.erb
<h2>this is the edit page for tasks</h2>

<p><%= link_to 'Back to project', project_path(@project) %></p>

<table>
  <tr>
    <th>No.</th>
    <th>Name</th>
    <th>Duration</th>
    <th>Start</th>
    <th>Finish</th>
    <th>Predecessors</th>
    <th>Resources</th>
  </tr>
  <%= form_for [@project, @task] do |f| %>
    <tr>
      <td><%= f.text_field :number %></td>
      <td><%= f.text_field :name %></td>
      <td><%= f.text_field :duration %></td>
      <td><%= f.text_field :start %></td>
      <td><%= f.text_field :finish %></td>
      <td><%= f.text_field :predecessors %></td>
      <td><%= f.text_field :resources %></td>
      <td><%= f.submit 'Submit', class: "button round" %></td>
    </tr>
  <%- end -%>
</table>

app/views/tasks/index.html.erb
<h2>this is the index page for tasks</h2>

<p><%= link_to 'Add a new task', new_task_path %></p>

<% if !@tasks.empty? %>
  <table>
    <tr>
      <th>No.</th>
      <th>Name</th>
      <th>Duration</th>
      <th>Start</th>
      <th>Finish</th>
      <th>Predecessors</th>
      <th>Resources</th>
    </tr>

    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.number %></td>
        <td><%= task.name %></td>
        <td><%= task.duration %></td>
        <td><%= task.start %></td>
        <td><%= task.finish %></td>
        <td><%= task.predecessors %></td>
        <td><%= task.resources %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Delete', task_path(task), method: :delete %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/tasks/new.html.erb
<h2>this is the new page for tasks</h2>

<p><%= link_to 'Back to timeline', project_tasks_path %></p>

<table>
  <tr>
    <th>No.</th>
    <th>Name</th>
    <th>Duration</th>
    <th>Start</th>
    <th>Finish</th>
    <th>Predecessors</th>
    <th>Resources</th>
  </tr>
  <%= form_for @task do |f| %>
    <tr>
      <td><%= f.text_field :number %></td>
      <td><%= f.text_field :name %></td>
      <td><%= f.text_field :duration %></td>
      <td><%= f.text_field :start %></td>
      <td><%= f.text_field :finish %></td>
      <td><%= f.text_field :predecessors %></td>
      <td><%= f.text_field :resources %></td>
      <td><%= f.submit 'Submit' %></td>
    </tr>
  <%- end -%>
</table>